
[config]
additional_profiles = [
  "all-default-tasks",
  "docs-all-modification-tasks",
  "ci-coverage-tasks",
  "ci-all-build-tasks",
  "ci-static-code-analysis-tasks",
  "publish-pre-cleanup",
  "multi-phase-tests"
]
